In [ ]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')


from google.colab import drive
drive.mount('/content/drive')
PATH ='/content/drive/MyDrive/tasty_share/'

Mounted at /content/drive


In [ ]:
rest= pd.read_csv(PATH+'v12.csv')
simpmood=pd.read_csv(PATH+'p_dis_words.csv')
simpmood

NM                             words
0   머리가복잡해      ['머리가복잡해','지쳐', '신나', '우울해']
1      답답해       ['답답해','우울해', '신나', '기분전환']
2      화가나   ['화가나','머리가복잡해', '에너지넘쳐', '지쳐']
3      우울해     ['우울해','신나', '답답해', '머리가복잡해']
4     기분전환       ['기분전환','센치해', '신나', '우울해']
5      행복해       ['행복해','즐거워', '무료해', '센치해']
6       신나       ['신나','우울해', '기분전환', '답답해']
7      즐거워       ['즐거워','행복해', '평온해', '센치해']
8    만족스러워  ['만족스러워','감성터질때', '기분전환', '센치해']
9      평온해       ['평온해','무료해', '즐거워', '행복해']
10     새로워    ['새로워','설레', '감성터질때', '만족스러워']
11      설레    ['설레','새로워', '감성터질때', '만족스러워']
12     무료해       ['무료해','평온해', '즐거워', '행복해']
13   감성터질때    ['감성터질때','만족스러워', '설레', '센치해']
14     외로워        ['외로워','설레', '평온해', '새로워']
15     센치해    ['센치해','기분전환', '즐거워', '감성터질때']
16     귀찮아        ['귀찮아','외로워', '새로워', '설레']
17      지쳐      ['지쳐','머리가복잡해', '신나', '우울해']
18   에너지넘쳐      ['에너지넘쳐','우울해', '답답해', '신나']
19   절망스러워   ['절망스러워','화가나', '답답해', '에너지넘쳐']
20     그리워       ['그리워','외로워', '귀찮아', '무료해']

In [ ]:
rest[['pmood']] = rest[['pmood']].astype('str')
rest['pmood'] =rest['pmood'].str.split(",")

In [ ]:
rest

idx         dayimg  ...           whenn         purpose
0      1   시골통돼지볶음.jpeg  ...  추운날,비오는날,날씨좋은날       술마시기좋은,식사
1      2    수림식당본점.jpeg  ...        추운날,비오는날      식사,데이트하기좋은
2      3      파나카B.jpeg  ...           날씨좋은날  데이트하기좋은,공부하기좋은
3      4    자마미등갈비.jpeg  ...        추운날,비오는날          술마시기좋은
4      5       의정서.jpeg  ...      비오는날,날씨좋은날  데이트하기좋은,사진찍기좋은
..   ...            ...  ...             ...             ...
244  246      마음한줄.jpeg  ...           날씨좋은날       식사,포장하기좋은
245  247     피자플래넷.jpeg  ...  날씨좋은날,추운날,비오는날          포장하기좋은
246  248  써브웨이부산대점.jpeg  ...           날씨좋은날    포장하기좋은,가벼운식사
247  249  피자나라치킨공주.jpeg  ...  날씨좋은날,추운날,비오는날       식사,포장하기좋은
248  250    카페묘한다방.jpeg  ...  날씨좋은날,추운날,비오는날  술마시기좋은,데이트하기좋은

[249 rows x 16 columns]

In [ ]:
import ast
for i in range(0,len(simpmood)):
  simpmood['words'][i] = ast.literal_eval(simpmood['words'][i])

In [ ]:
simpmood

NM                      words
0   머리가복잡해      [머리가복잡해, 지쳐, 신나, 우울해]
1      답답해       [답답해, 우울해, 신나, 기분전환]
2      화가나   [화가나, 머리가복잡해, 에너지넘쳐, 지쳐]
3      우울해     [우울해, 신나, 답답해, 머리가복잡해]
4     기분전환       [기분전환, 센치해, 신나, 우울해]
5      행복해       [행복해, 즐거워, 무료해, 센치해]
6       신나       [신나, 우울해, 기분전환, 답답해]
7      즐거워       [즐거워, 행복해, 평온해, 센치해]
8    만족스러워  [만족스러워, 감성터질때, 기분전환, 센치해]
9      평온해       [평온해, 무료해, 즐거워, 행복해]
10     새로워    [새로워, 설레, 감성터질때, 만족스러워]
11      설레    [설레, 새로워, 감성터질때, 만족스러워]
12     무료해       [무료해, 평온해, 즐거워, 행복해]
13   감성터질때    [감성터질때, 만족스러워, 설레, 센치해]
14     외로워        [외로워, 설레, 평온해, 새로워]
15     센치해    [센치해, 기분전환, 즐거워, 감성터질때]
16     귀찮아        [귀찮아, 외로워, 새로워, 설레]
17      지쳐      [지쳐, 머리가복잡해, 신나, 우울해]
18   에너지넘쳐      [에너지넘쳐, 우울해, 답답해, 신나]
19   절망스러워   [절망스러워, 화가나, 답답해, 에너지넘쳐]
20     그리워       [그리워, 외로워, 귀찮아, 무료해]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
rest['pmood'] = rest['pmood'].apply(lambda x : (' ').join(x))
u=count_vect.fit(rest['pmood'])
rest_mat_pmood=count_vect.transform(rest['pmood'])

simpmood['words'] = simpmood['words'].apply(lambda x : (' ').join(x))
key_mat_pmood=count_vect.transform(simpmood['words'])

In [ ]:
print(key_mat_pmood.toarray())

[[0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0]
 [1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0]
 [1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0]
 [1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1]
 [0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0]]


In [ ]:
######코사인 유사도#######
from sklearn.metrics.pairwise import cosine_similarity

pmood_sim	=cosine_similarity(key_mat_pmood,rest_mat_pmood)

print(pmood_sim.shape)
print(pmood_sim[:10])

(21, 249)
[[0.5        0.         0.         ... 0.16666667 0.37796447 0.16666667]
 [0.66666667 0.         0.         ... 0.16666667 0.75592895 0.16666667]
 [0.33333333 0.         0.         ... 0.16666667 0.         0.16666667]
 ...
 [0.33333333 0.61237244 0.61237244 ... 0.5        0.56694671 0.5       ]
 [0.33333333 0.         0.20412415 ... 0.16666667 0.18898224 0.5       ]
 [0.33333333 0.81649658 0.81649658 ... 0.66666667 0.56694671 0.33333333]]


In [ ]:
pmood_sim_sorted_ind =pmood_sim.argsort()[:, ::-1]
print(pmood_sim_sorted_ind[:7])

[[171 170  96 ...  65 138 124]
 [ 80  79 229 ... 138  53 207]
 [ 24 201 209 ... 189  98 124]
 ...
 [170 130  79 ...  78 199  76]
 [138 205  56 ...  73 225  96]
 [ 80  79 229 ... 138  53 207]]


In [ ]:
def find_sim_rest(key_name):
  name_key = simpmood[simpmood['NM']== key_name]

  name_index = name_key.index.values
  similar_indexes = sorted_ind[name_index, :12]

  print(similar_indexes)
  similar_indexes = similar_indexes.reshape(-1)
  return rest.iloc[similar_indexes]

In [ ]:
similar_rest = find_sim_rest('신나')
similar_rest
#sep_cos_weighted

[[ 80  79 229 247  43 170 179  96  73  45 127 183]]


idx          dayimg  ...           whenn         purpose
80    81      뉴숯불통닭.jpeg  ...        비오는날,추운날       식사,술마시기좋은
79    80      칠칠켄터키.jpeg  ...  날씨좋은날,비오는날,추운날       식사,술마시기좋은
229  231       모름지기.jpeg  ...        비오는날,추운날       술마시기좋은,식사
247  249   피자나라치킨공주.jpeg  ...  날씨좋은날,추운날,비오는날       식사,포장하기좋은
43    44      신천닭도리.jpeg  ...        비오는날,추운날          술마시기좋은
170  171         토모.jpeg  ...        추운날,비오는날  술마시기좋은,데이트하기좋은
179  180       짬뽕상회.jpeg  ...        비오는날,추운날    해장,식사,술마시기좋은
96    97      장수돌곱창.jpeg  ...        추운날,비오는날          술마시기좋은
73    74       돼지집딸.jpeg  ...  날씨좋은날,추운날,비오는날          술마시기좋은
45    46  촨촨향훠궈무한리필.jpeg  ...  비오는날,추운날,날씨좋은날              식사
127  128      조선화로집.jpeg  ...        추운날,비오는날          술마시기좋은
183  184        미식가.jpeg  ...        추운날,비오는날       식사,술마시기좋은

[12 rows x 16 columns]