In [ ]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')


from google.colab import drive
drive.mount('/content/drive')
PATH ='/content/drive/MyDrive/Colab code/'

Mounted at /content/drive


In [ ]:
rest= pd.read_csv(PATH+'v10.csv')
simrmood=pd.read_csv(PATH+'rDistance_among_words.csv')


In [ ]:
rest[['rmood']] = rest[['rmood']].astype('str')
rest['rmood'] =rest['rmood'].str.split(",")

In [ ]:
rest

idx           name  ...           whenn         purpose
0      0   시골통돼지볶음 부산대점  ...  추운날,비오는날,날씨좋은날       술마시기좋은,식사
1      1            톤쇼우  ...  날씨좋은날,비오는날,추운날              식사
2      2        수림식당 본점  ...        추운날,비오는날      식사,데이트하기좋은
3      3           파나카B  ...           날씨좋은날  데이트하기좋은,공부하기좋은
4      4         자마미등갈비  ...        추운날,비오는날          술마시기좋은
..   ...            ...  ...             ...             ...
246  246           마음한줄  ...           날씨좋은날       식사,포장하기좋은
247  247     피자플래넷 부산대점  ...  날씨좋은날,추운날,비오는날          포장하기좋은
248  248    써브웨이 부산부산대점  ...           날씨좋은날    포장하기좋은,가벼운식사
249  249  피자나라치킨공주 부산대점  ...  날씨좋은날,추운날,비오는날       식사,포장하기좋은
250  250        카페 묘한다방  ...  날씨좋은날,추운날,비오는날  술마시기좋은,데이트하기좋은

[251 rows x 15 columns]

In [ ]:
# # simrmood[['words']] = simrmood[['words']].astype('str')
# simrmood['words'] =simrmood['words'].str.split(",")

In [ ]:
simrmood

NM                                           words
0     정감있는    ['신선한', '학생감성', '소박한', '남다른', '유명한', '한국감성']
1    시끌벅적한    ['반전매력', '활기찬', '치맥감성', '활발한', '다양한', '기똥찬']
2      활발한   ['운치있는', '복잡한', '활기찬', '전통있는', '조그마한', '기똥찬']
3      친절한    ['진짜의', '남다른', '쾌적한', '인도감성', '기분좋은', '소박한']
4     일본감성     ['아기자기', '하얀', '감성자극', '좋은', '엔틱한', '캐쥬얼한']
..     ...                                             ...
167    시원한  ['유명한', '조그마한', '중국감성', '미묘한', '로컬의', '동남아감성']
168   캐쥬얼한  ['하얀', '전문적인', '기분좋은', '일본감성', '엔틱한', '분위기좋은']
169    다국적       ['퓨전의', '세련된', '멋있는', '트렌디한', '매운', '핫플']
170    퓨전의       ['다국적', '세련된', '멋있는', '트렌디한', '매운', '핫플']
171    소박한      ['쾌적한', '진짜의', '유명한', '남다른', '복잡한', '친절한']

[172 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

rest['rmood'] = rest['rmood'].apply(lambda x : (' ').join(x))
u=count_vect.fit(rest['rmood'])
rest_mat_rmood=count_vect.transform(rest['rmood'])

simrmood['words'] = simrmood['words'].apply(lambda x : (' ').join(x))
key_mat_rmood=count_vect.transform(simrmood['words'])

In [ ]:
print(u.get_feature_names())

['가벼운', '간단한', '감각적인', '감성있는', '개방적인', '건강한', '고급스러운', '귀여운', '그리운', '기똥찬', '기분좋은', '기쁜', '길거리감성', '깔끔한', '깨끗한', '나들이', '남다른', '눈부신', '다양한', '다이어트', '달달한', '대만감성', '도란도란', '독특한', '동남아감성', '따뜻한', '러블리한', '레트로감성', '로컬의', '루프탑', '매운', '멋있는', '모던한', '몽실몽실한', '미적인', '밝은', '베이지톤', '베이지톤의', '벨기에감성', '복잡한', '부드러운', '분위기좋은', '뷰가좋은', '브런치', '비쥬얼좋은', '빈티지한', '빛나는', '사랑스러운', '새로운', '색다른', '생기있는', '세련된', '소담한', '소박한', '소소한', '숨은', '숯불감성', '슬픈', '시골분위기', '시끄러운', '시끌벅적한', '시원한', '신기한', '신나는', '신선한', '심플한', '아기자기한', '아기자기한한', '아늑한', '아담한', '아름다운', '안락한', '알록달록한', '알찬', '어두운', '엔틱한', '예쁜', '옛날의', '오래된', '온화한', '우드톤', '운치있는', '웨이팅', '유럽감성', '유명한', '육수가진한', '은은한', '음악이있는', '이탈리아감성', '인도감성', '인스타감성', '인테리어예쁜', '일본감성', '잔잔한', '재미있는', '전문적인', '전통있는', '정갈한', '정감있는', '정겨운', '정성스러운', '조명이좋은', '조용한', '좋은', '주택개조', '중국감성', '즐거운', '진짜의', '집밥감성', '차분한', '청결한', '청량한', '추억', '치맥감성', '친근한', '친절한', '캐쥬얼한', '쾌적한', '클래식한', '태국감성', '테라스', '트렌디한', '특색있는', '편한', '포근한', '포장하기좋은', '포차감성', '푸짐한', '퓨전의', '프라이빗한', '프랑스감성', '학생감

In [ ]:
print(key_mat_rmood.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
######코사인 유사도#######
from sklearn.metrics.pairwise import cosine_similarity

rmood_sim	=cosine_similarity(key_mat_rmood,rest_mat_rmood)

print(rmood_sim.shape)
print(rmood_sim[:10])



(172, 251)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
rmood_sim_sorted_ind =rmood_sim.argsort()[:, ::-1]
print(rmood_sim_sorted_ind[:3])

[[250  78  91  90  89  88  87  86  85  84  83  82  81  80  79  77  62  76
   75  74  73  72  71  70  69  68  67  66  65  64  92  93  94  95 122 121
  120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103
  102 101 100  99  98  97  96  63  61 124  15  28  27  26  25  24  23  22
   21  20  19  18  17  16  14  60  13  12  11  10   9   8   7   6   5   4
    3   2   1  29  30  31  32  59  58  57  56  55  54  53  52  51  50  49
   48  47  46  45  44  43  42  41  40  39  38  37  36  35  34  33 123 125
  249 204 217 216 215 214 213 212 211 210 209 208 207 206 205 203 188 202
  201 200 199 198 197 196 195 194 193 192 191 190 218 219 220 221 248 247
  246 245 244 243 242 241 240 239 238 237 236 235 234 233 232 231 230 229
  228 227 226 225 224 223 222 189 187 126 141 154 153 152 151 150 149 148
  147 146 145 144 143 142 140 186 139 138 137 136 135 134 133 132 131 130
  129 128 127 155 156 157 158 185 184 183 182 181 180 179 178 177 176 175
  174 173 172 171 170 169 168 167 166 

In [ ]:
def find_sim_rest(df,sorted_ind, key_name):
  #인자로 입력된 rest DF에서 'name'칼럼이, 입력된 rest_name 데이터프레임 추출
  name_key = df[df['NM']== key_name]

  #key_name 가진 데이터프레임의 인덱스 객체를 ndarray로 반환하고
  #sorted_ind 인자로 입력된 key_sim_sorted_ind 객체에서
  #유사도 순으로 top_n개의 index 추출
  name_index = name_key.index.values
  similar_indexes = sorted_ind[name_index, :20]

  #top_n 2차원이므로 index 로 사용하기위해 array로 바꿔줘야 함.
  print(similar_indexes)
  similar_indexes = similar_indexes.reshape(-1)
  return rest.iloc[similar_indexes]

In [ ]:
similar_rest = find_sim_rest(simrmood, rmood_sim_sorted_ind, '인스타감성')
similar_rest
#sep_cos_weighted

[[250  78  91  90  89  88  87  86  85  84  83  82  81  80  79  77  62  76
   75  74]]


name quantity  ...           whenn             purpose
250        카페 묘한다방       중간  ...  날씨좋은날,추운날,비오는날      술마시기좋은,데이트하기좋은
78   강다짐 삼각김밥 부산대점       적음  ...  날씨좋은날,비오는날,추운날        가벼운식사,포장하기좋은
91           이솝페이블       중간  ...           날씨좋은날      데이트하기좋은,사진찍기좋은
90            카카오두       중간  ...           날씨좋은날  데이트하기좋은,수다떨기좋은,디저트
89       다락마을 부산대점       적음  ...           날씨좋은날          식사,데이트하기좋은
88             스시심       많음  ...      특별한날,날씨좋은날  데이트하기좋은,소개팅,대접하기좋은
87      롤링파스타 부산대점       중간  ...       날씨좋은날,추운날          식사,데이트하기좋은
86      배씨상회 부산대본점       많음  ...        비오는날,추운날      술마시기좋은,데이트하기좋은
85     파스타바니타 부산대점       많음  ...      특별한날,날씨좋은날             데이트하기좋은
84      정희옥스시 부산대점       중간  ...      날씨좋은날,비오는날          식사,데이트하기좋은
83           카페어리브       중간  ...           날씨좋은날      사진찍기좋은,데이트하기좋은
82              라프       중간  ...      날씨좋은날,비오는날   가벼운식사,브런치,데이트하기좋은
81        뉴숯불통닭 본점       중간  ...        비오는날,추운날           식사,술마시기좋은
80     칠칠켄터키 부산대본점       많음  ...  날씨좋은날,비오는날,추운날           식사,술마시기좋은
79       정직유부 부산대점       많음  ...  날씨좋은날,비오는날,추운날        가벼운식사,포장하기좋은
77            카페드팽       중간  ...  날씨좋은날,비오는날,추운날   공부하기좋은,과제하기좋은,디저트
62             카츠안       중간  ...           날씨좋은날                  식사
76       모구모구 베이커리       중간  ...  날씨좋은날,비오는날,추운날          포장하기좋은,디저트
75             삼세랑       많음  ...      날씨좋은날,비오는날      술마시기좋은,데이트하기좋은
74            돼지집딸       중간  ...  날씨좋은날,추운날,비오는날              술마시기좋은

[20 rows x 12 columns]